apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
spec:
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: web-dvwa
        image: docker.io/vulnerables/web-dvwa:latest
        env:
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dvwa
spec:
  type: LoadBalancer
  selector:
    app: dvwa
  ports:
  - name: http
    port: 80
    targetPort: 80
